### ISSUE TITLE
Which dataset does tree.md refers . I have checked mot17 its not like this 

### ISSUE THREAD

**Issue by ajithvcoder** [yoyomimi/TNT_pytorch#2]
Could you let me know which dataset does tree.md refers and could give the link for it

**Comment by yoyomimi** [comment]
The dataset is KITTI, but the annotation file has been transformed into another type. The format of the dataset annotation is noted in the datasets/ObjtrackDataset.py. The annotation is in a coco liked type. You are supposed to transform your dataset annotation file to .json file with this format, or you need to write your own dataset file.

**Comment by ajithvcoder** [comment]
@yoyomimi thanks for a quick reply which one of these you used in http://www.cvlibs.net/datasets/kitti/eval_tracking.php

1. Download left color images of tracking data set (15 GB)
2.Download right color images, if you want to use stereo information (15 GB)
3.Download Velodyne point clouds, if you want to use laser information (35 GB)

**Comment by yoyomimi** [comment]
> @yoyomimi thanks for a quick reply which one of these you used in http://www.cvlibs.net/datasets/kitti/eval_tracking.php
> 
> 1. Download left color images of tracking data set (15 GB)
>    2.Download right color images, if you want to use stereo information (15 GB)
>    3.Download Velodyne point clouds, if you want to use laser information (35 GB)

1. Download left color images of tracking data set (15 GB)

**Comment by ajithvcoder** [comment]
thanks
